
package stub_manage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ManageServiceImplService", targetNamespace = "http://www.polytech.unice.fr/tcf", wsdlLocation = "http://localhost:8080/demo/webservices/ManageServiceImpl?wsdl")
public class ManageServiceImplService
    extends Service
{

    private final static URL MANAGESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MANAGESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName MANAGESERVICEIMPLSERVICE_QNAME = new QName("http://www.polytech.unice.fr/tcf", "ManageServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/demo/webservices/ManageServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MANAGESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        MANAGESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ManageServiceImplService() {
        super(__getWsdlLocation(), MANAGESERVICEIMPLSERVICE_QNAME);
    }

    public ManageServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MANAGESERVICEIMPLSERVICE_QNAME, features);
    }

    public ManageServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, MANAGESERVICEIMPLSERVICE_QNAME);
    }

    public ManageServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MANAGESERVICEIMPLSERVICE_QNAME, features);
    }

    public ManageServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManageServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ManageService
     */
    @WebEndpoint(name = "ManageServiceImplPort")
    public ManageService getManageServiceImplPort() {
        return super.getPort(new QName("http://www.polytech.unice.fr/tcf", "ManageServiceImplPort"), ManageService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManageService
     */
    @WebEndpoint(name = "ManageServiceImplPort")
    public ManageService getManageServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.polytech.unice.fr/tcf", "ManageServiceImplPort"), ManageService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MANAGESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw MANAGESERVICEIMPLSERVICE_EXCEPTION;
        }
        return MANAGESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
