
package stub;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TcfService", targetNamespace = "http://webservice.tcf.polytech.unice.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TcfService {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "ingredient_list", targetNamespace = "")
    @RequestWrapper(localName = "listIngredients", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.ListIngredients")
    @ResponseWrapper(localName = "listIngredientsResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.ListIngredientsResponse")
    public List<String> listIngredients();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "ingredient_list", targetNamespace = "")
    @RequestWrapper(localName = "listIngredientsDetail", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.ListIngredientsDetail")
    @ResponseWrapper(localName = "listIngredientsDetailResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.ListIngredientsDetailResponse")
    public List<String> listIngredientsDetail();

    /**
     * 
     * @param adresse
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "isExist", targetNamespace = "")
    @RequestWrapper(localName = "boutiqueIsExist", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.BoutiqueIsExist")
    @ResponseWrapper(localName = "boutiqueIsExistResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.BoutiqueIsExistResponse")
    public boolean boutiqueIsExist(
        @WebParam(name = "adresse", targetNamespace = "")
        String adresse);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "all_boutiques", targetNamespace = "")
    @RequestWrapper(localName = "listBoutiques", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.ListBoutiques")
    @ResponseWrapper(localName = "listBoutiquesResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.ListBoutiquesResponse")
    public List<String> listBoutiques();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "band", targetNamespace = "")
    @RequestWrapper(localName = "validCommande", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.ValidCommande")
    @ResponseWrapper(localName = "validCommandeResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.ValidCommandeResponse")
    public String validCommande();

    /**
     * 
     * @param magasin
     * @param owner
     */
    @WebMethod
    @RequestWrapper(localName = "createCommand", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.CreateCommand")
    @ResponseWrapper(localName = "createCommandResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.CreateCommandResponse")
    public void createCommand(
        @WebParam(name = "owner", targetNamespace = "")
        String owner,
        @WebParam(name = "magasin", targetNamespace = "")
        String magasin);

    /**
     * 
     * @param price
     * @param name
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "created", targetNamespace = "")
    @RequestWrapper(localName = "creatIngredient", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.CreatIngredient")
    @ResponseWrapper(localName = "creatIngredientResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.CreatIngredientResponse")
    public boolean creatIngredient(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "price", targetNamespace = "")
        double price);

    /**
     * 
     * @param adresse
     * @param ouvert
     * @param taxe
     * @param fermer
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "boutiquecreated", targetNamespace = "")
    @RequestWrapper(localName = "creerBoutique", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.CreerBoutique")
    @ResponseWrapper(localName = "creerBoutiqueResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.CreerBoutiqueResponse")
    public boolean creerBoutique(
        @WebParam(name = "adresse", targetNamespace = "")
        String adresse,
        @WebParam(name = "ouvert", targetNamespace = "")
        XMLGregorianCalendar ouvert,
        @WebParam(name = "fermer", targetNamespace = "")
        XMLGregorianCalendar fermer,
        @WebParam(name = "taxe", targetNamespace = "")
        double taxe);

    /**
     * 
     * @param name
     */
    @WebMethod
    @RequestWrapper(localName = "addIngredientToCookie", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.AddIngredientToCookie")
    @ResponseWrapper(localName = "addIngredientToCookieResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.AddIngredientToCookieResponse")
    public void addIngredientToCookie(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param adresse
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "statis_nbCookie", targetNamespace = "")
    @RequestWrapper(localName = "viewStatistiqueCookies", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.ViewStatistiqueCookies")
    @ResponseWrapper(localName = "viewStatistiqueCookiesResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.ViewStatistiqueCookiesResponse")
    public int viewStatistiqueCookies(
        @WebParam(name = "adresse", targetNamespace = "")
        String adresse);

    /**
     * 
     * @param adresse
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "boutique_Detail", targetNamespace = "")
    @RequestWrapper(localName = "getBoutique", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.GetBoutique")
    @ResponseWrapper(localName = "getBoutiqueResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.GetBoutiqueResponse")
    public String getBoutique(
        @WebParam(name = "adresse", targetNamespace = "")
        String adresse);

    /**
     * 
     * @param name
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "isExist", targetNamespace = "")
    @RequestWrapper(localName = "ingredientIsExist", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.IngredientIsExist")
    @ResponseWrapper(localName = "ingredientIsExistResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.IngredientIsExistResponse")
    public boolean ingredientIsExist(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param name
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "deleted", targetNamespace = "")
    @RequestWrapper(localName = "supprimerIngredient", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.SupprimerIngredient")
    @ResponseWrapper(localName = "supprimerIngredientResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.SupprimerIngredientResponse")
    public boolean supprimerIngredient(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param adresse
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "statis_nbCommande", targetNamespace = "")
    @RequestWrapper(localName = "viewStatistiqueCommande", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.ViewStatistiqueCommande")
    @ResponseWrapper(localName = "viewStatistiqueCommandeResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub.ViewStatistiqueCommandeResponse")
    public int viewStatistiqueCommande(
        @WebParam(name = "adresse", targetNamespace = "")
        String adresse);

}
