
package stub_processCmd;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProcessCommandService", targetNamespace = "http://webservice.tcf.polytech.unice.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProcessCommandService {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "ingredient_list", targetNamespace = "")
    @RequestWrapper(localName = "listIngredients", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.ListIngredients")
    @ResponseWrapper(localName = "listIngredientsResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.ListIngredientsResponse")
    public List<String> listIngredients();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "ingredient_list", targetNamespace = "")
    @RequestWrapper(localName = "listIngredientsDetail", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.ListIngredientsDetail")
    @ResponseWrapper(localName = "listIngredientsDetailResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.ListIngredientsDetailResponse")
    public List<String> listIngredientsDetail();

    /**
     * 
     * @param name
     */
    @WebMethod
    @RequestWrapper(localName = "createNewCookie", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.CreateNewCookie")
    @ResponseWrapper(localName = "createNewCookieResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.CreateNewCookieResponse")
    public void createNewCookie(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "all_boutiques", targetNamespace = "")
    @RequestWrapper(localName = "listBoutiques", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.ListBoutiques")
    @ResponseWrapper(localName = "listBoutiquesResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.ListBoutiquesResponse")
    public List<String> listBoutiques();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "band", targetNamespace = "")
    @RequestWrapper(localName = "validCommande", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.ValidCommande")
    @ResponseWrapper(localName = "validCommandeResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.ValidCommandeResponse")
    public String validCommande();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "cookie_list", targetNamespace = "")
    @RequestWrapper(localName = "listCookies", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.ListCookies")
    @ResponseWrapper(localName = "listCookiesResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.ListCookiesResponse")
    public List<String> listCookies();

    /**
     * 
     * @param magasin
     * @param owner
     */
    @WebMethod
    @RequestWrapper(localName = "createCommand", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.CreateCommand")
    @ResponseWrapper(localName = "createCommandResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.CreateCommandResponse")
    public void createCommand(
        @WebParam(name = "owner", targetNamespace = "")
        String owner,
        @WebParam(name = "magasin", targetNamespace = "")
        String magasin);

    /**
     * 
     * @param name
     */
    @WebMethod
    @RequestWrapper(localName = "chosirUnCookie", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.ChosirUnCookie")
    @ResponseWrapper(localName = "chosirUnCookieResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.ChosirUnCookieResponse")
    public void chosirUnCookie(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "validNewCookie", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.ValidNewCookie")
    @ResponseWrapper(localName = "validNewCookieResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.ValidNewCookieResponse")
    public void validNewCookie();

    /**
     * 
     * @param adresse
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "boutique_Detail", targetNamespace = "")
    @RequestWrapper(localName = "getBoutique", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.GetBoutique")
    @ResponseWrapper(localName = "getBoutiqueResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.GetBoutiqueResponse")
    public String getBoutique(
        @WebParam(name = "adresse", targetNamespace = "")
        String adresse);

    /**
     * 
     * @param name
     */
    @WebMethod
    @RequestWrapper(localName = "addIngredientToNewCookie", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.AddIngredientToNewCookie")
    @ResponseWrapper(localName = "addIngredientToNewCookieResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.AddIngredientToNewCookieResponse")
    public void addIngredientToNewCookie(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
