
package stub_processCmd;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProcessCommandServiceImplService", targetNamespace = "http://www.polytech.unice.fr/tcf", wsdlLocation = "http://localhost:8080/demo/webservices/ProcessCommandServiceImpl?wsdl")
public class ProcessCommandServiceImplService
    extends Service
{

    private final static URL PROCESSCOMMANDSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROCESSCOMMANDSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName PROCESSCOMMANDSERVICEIMPLSERVICE_QNAME = new QName("http://www.polytech.unice.fr/tcf", "ProcessCommandServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/demo/webservices/ProcessCommandServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROCESSCOMMANDSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        PROCESSCOMMANDSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ProcessCommandServiceImplService() {
        super(__getWsdlLocation(), PROCESSCOMMANDSERVICEIMPLSERVICE_QNAME);
    }

    public ProcessCommandServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROCESSCOMMANDSERVICEIMPLSERVICE_QNAME, features);
    }

    public ProcessCommandServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, PROCESSCOMMANDSERVICEIMPLSERVICE_QNAME);
    }

    public ProcessCommandServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROCESSCOMMANDSERVICEIMPLSERVICE_QNAME, features);
    }

    public ProcessCommandServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessCommandServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProcessCommandService
     */
    @WebEndpoint(name = "ProcessCommandServiceImplPort")
    public ProcessCommandService getProcessCommandServiceImplPort() {
        return super.getPort(new QName("http://www.polytech.unice.fr/tcf", "ProcessCommandServiceImplPort"), ProcessCommandService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessCommandService
     */
    @WebEndpoint(name = "ProcessCommandServiceImplPort")
    public ProcessCommandService getProcessCommandServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.polytech.unice.fr/tcf", "ProcessCommandServiceImplPort"), ProcessCommandService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROCESSCOMMANDSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw PROCESSCOMMANDSERVICEIMPLSERVICE_EXCEPTION;
        }
        return PROCESSCOMMANDSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
