
package stub_processCmd;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProcessCommandService", targetNamespace = "http://webservice.tcf.polytech.unice.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProcessCommandService {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "all_boutiques", targetNamespace = "")
    @RequestWrapper(localName = "listBoutiques", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.ListBoutiques")
    @ResponseWrapper(localName = "listBoutiquesResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.ListBoutiquesResponse")
    public List<String> listBoutiques();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "band", targetNamespace = "")
    @RequestWrapper(localName = "validCommande", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.ValidCommande")
    @ResponseWrapper(localName = "validCommandeResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.ValidCommandeResponse")
    public String validCommande();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "ingredient_list", targetNamespace = "")
    @RequestWrapper(localName = "listIngredientsDetail", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.ListIngredientsDetail")
    @ResponseWrapper(localName = "listIngredientsDetailResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.ListIngredientsDetailResponse")
    public List<String> listIngredientsDetail();

    /**
     * 
     * @param magasin
     * @param owner
     */
    @WebMethod
    @RequestWrapper(localName = "createCommand", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.CreateCommand")
    @ResponseWrapper(localName = "createCommandResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.CreateCommandResponse")
    public void createCommand(
        @WebParam(name = "owner", targetNamespace = "")
        String owner,
        @WebParam(name = "magasin", targetNamespace = "")
        String magasin);

    /**
     * 
     * @param name
     */
    @WebMethod
    @RequestWrapper(localName = "addIngredientToCookie", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.AddIngredientToCookie")
    @ResponseWrapper(localName = "addIngredientToCookieResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.AddIngredientToCookieResponse")
    public void addIngredientToCookie(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param adresse
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "boutique_Detail", targetNamespace = "")
    @RequestWrapper(localName = "getBoutique", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.GetBoutique")
    @ResponseWrapper(localName = "getBoutiqueResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.GetBoutiqueResponse")
    public String getBoutique(
        @WebParam(name = "adresse", targetNamespace = "")
        String adresse);

    /**
     * 
     * @param adresse
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "statis_nbCommande", targetNamespace = "")
    @RequestWrapper(localName = "viewStatistiqueCommande", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.ViewStatistiqueCommande")
    @ResponseWrapper(localName = "viewStatistiqueCommandeResponse", targetNamespace = "http://webservice.tcf.polytech.unice.fr/", className = "stub_processCmd.ViewStatistiqueCommandeResponse")
    public int viewStatistiqueCommande(
        @WebParam(name = "adresse", targetNamespace = "")
        String adresse);

}
